name: Build test

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        env:
          NG_CLI_VERSION: 12.0.1
          NODE_VERSION: 14.17.0
        run: |
          docker build \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg NODE_VERSION=${NODE_VERSION} \
            --build-arg NG_CLI_VERSION=${NG_CLI_VERSION} \
            -t bmeme/angular-dev:${NG_CLI_VERSION}-${NODE_VERSION} .
